version: '3.8'

services:
  text-to-statistical-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text-statistical-analyzer
    environment:
      # 환경변수 설정 (실제 사용시 .env 파일에서 로드)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-gpt-4o}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    volumes:
      # 데이터 및 결과 디렉토리 마운트
      - ./input_data:/app/input_data
      - ./output_results:/app/output_results
      - ./logs:/app/logs
      # 개발시 코드 변경사항 반영
      - ./core:/app/core
      - ./llm_services:/app/llm_services
      - ./data_processing:/app/data_processing
      - ./rag_system:/app/rag_system
      - ./code_execution:/app/code_execution
      - ./reporting:/app/reporting
      - ./config:/app/config
    working_dir: /app
    # 기본 명령어 (오버라이드 가능)
    command: ["python", "main_runner.py", "--help"]
    # 네트워크 설정
    networks:
      - statistical-network
    # 재시작 정책
    restart: unless-stopped

  # 개발용 주피터 노트북 서비스 (선택사항)
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: statistical-jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/app
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
    networks:
      - statistical-network
    profiles:
      - dev

networks:
  statistical-network:
    driver: bridge

volumes:
  notebooks:
    driver: local 