[tool.poetry]
name = "weighted-mtp"
version = "0.1.0"
description = "weighted_mtp using PPO critic function"
authors = ["Deepsix"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
